// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbYy_6MHd9ypqLm0tJw9Hhd795EidC2hE',
    appId: '1:233843947217:web:c57d98bccce000314337f0',
    messagingSenderId: '233843947217',
    projectId: 'file-app-6563f',
    authDomain: 'file-app-6563f.firebaseapp.com',
    storageBucket: 'file-app-6563f.firebasestorage.app',
    measurementId: 'G-KY0DPRKKJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOSkt74bsWsoNmFPMzECUT-TYme7R0r5k',
    appId: '1:233843947217:android:1a73888514741cd24337f0',
    messagingSenderId: '233843947217',
    projectId: 'file-app-6563f',
    storageBucket: 'file-app-6563f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXqYMd44hmI7xNCejpI13UyTl664gMsnA',
    appId: '1:233843947217:ios:52bbd9290f7d91af4337f0',
    messagingSenderId: '233843947217',
    projectId: 'file-app-6563f',
    storageBucket: 'file-app-6563f.firebasestorage.app',
    iosBundleId: 'com.example.imagesAppFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXqYMd44hmI7xNCejpI13UyTl664gMsnA',
    appId: '1:233843947217:ios:52bbd9290f7d91af4337f0',
    messagingSenderId: '233843947217',
    projectId: 'file-app-6563f',
    storageBucket: 'file-app-6563f.firebasestorage.app',
    iosBundleId: 'com.example.imagesAppFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbYy_6MHd9ypqLm0tJw9Hhd795EidC2hE',
    appId: '1:233843947217:web:020fd28e1a6b34144337f0',
    messagingSenderId: '233843947217',
    projectId: 'file-app-6563f',
    authDomain: 'file-app-6563f.firebaseapp.com',
    storageBucket: 'file-app-6563f.firebasestorage.app',
    measurementId: 'G-G7T9M4M5JW',
  );
}
